// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteAction(arg1, arg2) {
  return window['go']['main']['App']['ExecuteAction'](arg1, arg2);
}

export function FocusWindow() {
  return window['go']['main']['App']['FocusWindow']();
}

export function GetQuickActions(arg1) {
  return window['go']['main']['App']['GetQuickActions'](arg1);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function ProcessFile(arg1, arg2) {
  return window['go']['main']['App']['ProcessFile'](arg1, arg2);
}

export function SetPaletteExpanded(arg1, arg2) {
  return window['go']['main']['App']['SetPaletteExpanded'](arg1, arg2);
}
