// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CaptureArea(arg1:number,arg2:number,arg3:number,arg4:number):Promise<main.SnapshotResult>;

export function ExecuteAction(arg1:string,arg2:string):Promise<main.ProcessResult>;

export function FadeInWindow(arg1:number):Promise<main.ProcessResult>;

export function FocusWindow():Promise<void>;

export function GetQuickActions(arg1:string):Promise<Array<main.QuickAction>>;

export function GetVoiceStatus():Promise<main.VoiceStatus>;

export function MinimizeWindow():Promise<void>;

export function ProcessFile(arg1:string,arg2:string):Promise<main.ProcessResult>;

export function SetInputImeReady():Promise<main.ProcessResult>;

export function SetPaletteExpanded(arg1:boolean,arg2:number,arg3:Array<number>):Promise<void>;

export function SetWindowContentHeight(arg1:number):Promise<void>;

export function ToggleVoiceInput():Promise<main.ProcessResult>;
