// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteAction(arg1:string,arg2:string):Promise<main.ProcessResult>;

export function FocusWindow():Promise<void>;

export function GetQuickActions(arg1:string):Promise<Array<main.QuickAction>>;

export function MinimizeWindow():Promise<void>;

export function ProcessFile(arg1:string,arg2:string):Promise<main.ProcessResult>;

export function SetPaletteExpanded(arg1:boolean,arg2:number):Promise<void>;
