// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureArea(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CaptureArea'](arg1, arg2, arg3, arg4);
}

export function ExecuteAction(arg1, arg2) {
  return window['go']['main']['App']['ExecuteAction'](arg1, arg2);
}

export function FadeInWindow(arg1) {
  return window['go']['main']['App']['FadeInWindow'](arg1);
}

export function FocusWindow() {
  return window['go']['main']['App']['FocusWindow']();
}

export function GetQuickActions(arg1) {
  return window['go']['main']['App']['GetQuickActions'](arg1);
}

export function GetVoiceStatus() {
  return window['go']['main']['App']['GetVoiceStatus']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function ProcessFile(arg1, arg2) {
  return window['go']['main']['App']['ProcessFile'](arg1, arg2);
}

export function SetInputImeReady() {
  return window['go']['main']['App']['SetInputImeReady']();
}

export function SetPaletteExpanded(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPaletteExpanded'](arg1, arg2, arg3);
}

export function SetWindowContentHeight(arg1) {
  return window['go']['main']['App']['SetWindowContentHeight'](arg1);
}

export function ToggleVoiceInput() {
  return window['go']['main']['App']['ToggleVoiceInput']();
}
