// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetA2UIIngestURL() {
  return window['go']['main']['App']['GetA2UIIngestURL']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetFtbShellStatus() {
  return window['go']['main']['App']['GetFtbShellStatus']();
}

export function GetWsHubStatus() {
  return window['go']['main']['App']['GetWsHubStatus']();
}

export function GetWsUrl() {
  return window['go']['main']['App']['GetWsUrl']();
}

export function StartWsFakePump() {
  return window['go']['main']['App']['StartWsFakePump']();
}

export function StopWsFakePump() {
  return window['go']['main']['App']['StopWsFakePump']();
}
