// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {poc} from '../models';

export function GetA2UIIngestURL():Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetFtbShellStatus():Promise<poc.ShellFtbStatus>;

export function GetWsHubStatus():Promise<poc.HubStatus>;

export function GetWsUrl():Promise<string>;

export function StartWsFakePump():Promise<void>;

export function StopWsFakePump():Promise<void>;
